Repository khanturtle/WeMakePlay, pull requests merged in 2024-01, with the labels that each got.

#3 feat: BaseEntity 생성
  src/main/java/com/wemakeplay/wemakeplay/global/entity/BaseEntity.java
Labels: feat

#5 feature/signUp-create
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/repository/UserRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/service/UserService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#7 Feature/board
  .gitignore
  settings.gradle
  src/main/java/com/wemakeplay/wemakeplay/domain/attendboard/AttendBoard.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendboard/AttendBoardRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendboard/Participation.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/repository/BoardRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/repository/UserRepository.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
  src/main/resources/application.properties
Labels: feat

#8 Feature/admin
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/controller/AdminController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/service/AdminService.java
Labels: feat

#9 Feature/board
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
Labels: fix

#12 Feature/comment-create
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/controller/AdminController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/service/AdminService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/controller/CommentController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/dto/request/CommentRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/entity/Comment.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/repository/CommentRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/service/CommentService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#13 Feature/comment-update
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/controller/CommentController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/entity/Comment.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/service/CommentService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#16 Feature/team 팀 기능구현
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeam.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/Participation.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/entity/Team.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/repository/TeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#21 Feature/like-delete
  src/main/java/com/wemakeplay/wemakeplay/domain/like/controller/LikeController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/like/dto/LikeResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/like/repository/LikeRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/like/service/LikeService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat, refactor

#22 Feature/follow-create
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/Follow.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/controller/FollowController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/dto/FollowResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/entity/Follow.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/repository/FollowRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/service/FollowService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#25 fix: 보드 가입 기능
  src/main/java/com/wemakeplay/wemakeplay/domain/attendboard/AttendBoard.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
Labels: fix

#26 Feature/follow-get
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/service/CommentService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/controller/FollowController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/dto/FollowerResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/dto/FollowingResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/entity/Follow.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/repository/FollowRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/service/FollowService.java
Labels: feat, fix

#27 fix: 보드 가입 기능
  src/main/java/com/wemakeplay/wemakeplay/domain/attendboard/AttendBoard.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendboard/AttendBoardRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat, fix

#28 Feature/user-get
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardViewResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/repository/BoardRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/follow/repository/FollowRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/dto/response/UserProfileResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/service/UserService.java
Labels: feat

#30 Feature/team 인원수 추가, 가입 추가
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeam.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/entity/Team.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
Labels: feat

#29 Feature/board expiration
  src/main/java/com/wemakeplay/wemakeplay/domain/board/BoardScheduler.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/repository/BoardRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#31 Feature/admin-get/delete
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/controller/AdminController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/service/AdminService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/service/UserService.java
Labels: feat

#34 Feature/player-get
  src/main/java/com/wemakeplay/wemakeplay/domain/like/repository/LikeRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/player/controller/PlayerController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/player/dto/TopPlayerResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/player/service/PlayerService.java
Labels: feat

#32 Feature/board quit
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
Labels: feat

#33 Feature/team 탈퇴 기능 추가
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeam.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/entity/Team.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#35 feat: 보드 참여자 리스트 출력
  src/main/java/com/wemakeplay/wemakeplay/domain/admin/controller/AdminController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardViewResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserController.java
Labels: feat

#37 Feature/team 문서 수정 및 오류 수정
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeam.java
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamViewResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/entity/Team.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/repository/TeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
  src/main/java/com/wemakeplay/wemakeplay/global/config/WebSecurityConfig.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#38 Feature/front signup
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/dto/request/SignupRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/global/config/WebSecurityConfig.java
  src/main/resources/templates/login-j.html
  src/main/resources/templates/mainPage-j.html
  src/main/resources/templates/signup-j.html
Labels: feat

#39 Feature/html
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login-j.html
  src/main/resources/templates/mainPage-j.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/signup-j.html
Labels: feat, fix, front

#36 feature:팀 강퇴 기능 추가
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/entity/Team.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/repository/UserRepository.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
Labels: feat

#40 feat: 보드 전체 조회
  build.gradle
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardRequestDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardViewResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/java/com/wemakeplay/wemakeplay/global/config/WebSecurityConfig.java
  src/main/resources/templates/board.html
  src/main/resources/templates/boardForm.html
  src/main/resources/templates/boardMain.html
Labels: feat, front

#41 Feature/html
  src/main/java/com/wemakeplay/wemakeplay/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/wemakeplay/wemakeplay/global/util/JwtUtil.java
Labels: fix

#42 feat: 보드 가입 수락/거절
  build.gradle
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/entity/User.java
  src/main/java/com/wemakeplay/wemakeplay/global/config/WebSecurityConfig.java
  src/main/java/com/wemakeplay/wemakeplay/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/wemakeplay/wemakeplay/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/wemakeplay/wemakeplay/global/security/UserDetailsServiceImpl.java
  src/main/resources/templates/board.html
  src/main/resources/templates/boardAttender.html
  src/main/resources/templates/boardForm.html
  src/main/resources/templates/editBoardForm.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login-j.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/playSpace.html
Labels: feat, front

#43 feature : 채팅 추가
  build.gradle
  src/main/java/com/wemakeplay/wemakeplay/domain/chat/Chat.java
  src/main/java/com/wemakeplay/wemakeplay/domain/chat/config/WebSocketConfig.java
  src/main/java/com/wemakeplay/wemakeplay/domain/chat/handler/WebSocketHandler.java
Labels: feat

#44 Feature/html
  src/main/java/com/wemakeplay/wemakeplay/domain/player/controller/PlayerViewController.java
  src/main/resources/templates/login-j.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/topPlayer.html
Labels: feat, fix, front

#48 Feature/boardfront design
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardViewResponseDto.java
  src/main/resources/static/image/sports/농구공.png
  src/main/resources/static/image/sports/야구공.png
  src/main/resources/static/image/sports/축구공.png
  src/main/resources/templates/board.html
  src/main/resources/templates/boardForm.html
  src/main/resources/templates/playSpace.html
Labels: feat, fix, front

#49 Feature/html
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/resources/templates/followerList.html
  src/main/resources/templates/followingList.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/topPlayer.html
  src/main/resources/templates/userProfile.html
Labels: fix, front

#50 feat: 팔로우, 좋아요 생성
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/resources/templates/myPage.html
  src/main/resources/templates/userFollowerList.html
  src/main/resources/templates/userFollowingList.html
  src/main/resources/templates/userProfile.html
Labels: feat, front

#51 Feature/boardfront paging
  .gitignore
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/resources/templates/PlaySpace/BoardAttend/allowedAttender.html
  src/main/resources/templates/PlaySpace/BoardAttend/boardAttender.html
  src/main/resources/templates/PlaySpace/Comment/edit-comment.html
  src/main/resources/templates/PlaySpace/board.html
  src/main/resources/templates/PlaySpace/boardForm.html
  src/main/resources/templates/PlaySpace/editBoardForm.html
  src/main/resources/templates/PlaySpace/playSpace.html
  src/main/resources/templates/index.html
  src/main/resources/templates/teamAttend.html
Labels: feat, fix, front

#53 feat: 프론트 보드에서 유저 조회 기능 구현
  src/main/java/com/wemakeplay/wemakeplay/domain/board/dto/BoardResponseDto.java
  src/main/resources/templates/PlaySpace/board.html
Labels: feat, fix, front

#55 Chore: CI/CD 관련 파일추가
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
  src/test/java/com/wemakeplay/wemakeplay/WemakeplayApplicationTests.java
Labels: docs

#54 feat: 메인 페이지 내용 연동
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/player/service/PlayerService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/resources/templates/PlaySpace/board.html
  src/main/resources/templates/mainPage.html
Labels: feat, front

#56 Feature/team 팀 단건 조회, 참여자 확인
  src/main/java/com/wemakeplay/wemakeplay/domain/attendteam/AttendTeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/dto/TeamViewResponseDto.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/repository/TeamRepository.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/resources/templates/allowedAttenderTeam.html
  src/main/resources/templates/team.html
  src/main/resources/templates/teamAttend.html
Labels: feat, docs

#57 Feature/html
  src/main/resources/templates/PlaySpace/board.html
  src/main/resources/templates/team.html
Labels: fix, front

#58 docs: application.yml 파일 커밋 권한 설정
  .gitignore
Labels: fix, docs

#59 fix: application.yml DB 정보 수정
  src/main/resources/application.yml
Labels: fix

#60 Feature/team 팀 페이지징 구현 및 에러코드 수정
  src/main/java/com/wemakeplay/wemakeplay/domain/team/controller/TeamViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
  src/main/resources/templates/teamAttend.html
Labels: feat, docs

#61 Feature/board exception
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/controller/CommentController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/comment/service/CommentService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
  src/main/resources/templates/PlaySpace/board.html
  src/main/resources/templates/signup-j.html
Labels: fix

#71 refactor: 팀 서비스 코드 리펙토링
  src/main/java/com/wemakeplay/wemakeplay/domain/team/service/TeamService.java
Labels: refactor

#72 feat: 배드민턴 추가
  src/main/resources/static/image/sports/셔틀콕.png
  src/main/resources/templates/PlaySpace/boardForm.html
  src/main/resources/templates/PlaySpace/playSpace.html
Labels: feat, front

#73 Feature/boardfront paging
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
Labels: fix, front

#74 Feature/board quit
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/java/com/wemakeplay/wemakeplay/global/exception/ErrorCode.java
  src/main/resources/templates/PlaySpace/board.html
Labels: feat, fix, front

#75 Feature/front fix
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/controller/BoardViewController.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/entity/Board.java
  src/main/java/com/wemakeplay/wemakeplay/domain/board/service/BoardService.java
  src/main/resources/templates/PlaySpace/board.html
  src/main/resources/templates/PlaySpace/boardForm.html
  src/main/resources/templates/PlaySpace/editBoardForm.html
  src/main/resources/templates/signup-j.html
Labels: feat, fix, front

#79 Feature/html
  src/main/java/com/wemakeplay/wemakeplay/domain/user/controller/UserViewControllerJ.java
  src/main/resources/templates/PlaySpace/board.html
  src/main/resources/templates/PlaySpace/playSpace.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mainPage.html
  src/main/resources/templates/team.html
  src/main/resources/templates/topPlayer.html
Labels: fix

#81 fix: userProfile.html 좋아요, 팔로우 시 페이지 새로고침
  src/main/resources/templates/userProfile.html
Labels: fix

#82 fix: 로그인 실패시 수정
  src/main/resources/templates/login-j.html
Labels: fix
